### ISSUE TITLE
Release result

### ISSUE THREAD

**Issue by nagthanm** [fit-together-tv/ft-issue-report#14]
### Reproduction Steps
* Open [app.chuongnau.com](https://app.chuongnau.com)
* Choose `view question form`
* Choose tab `Publish exam/Answer`
* Click `Release result`

### Actual Behavior
`Once you release the results, you will no longer be able to withhold them. Are you sure?`

### Question and  suggest improvement
I would prefer a option to withhold the exam result and I may understand why you choose not to withhold them so I try to express my opinion as simple as possible:

* Reason to not withhold them:
  * If the published exam is an important exam: semester test, final exam, for example...
  * You mentioned some people would not change the question form after they have taken the tests. 

* Reason to withhold them:
  * If the published exam is not an important exam: practice exam, entrance exam, for example.
  * If users have the demand to use these exams for the other classes. They could also use this year important exam for next year student to practice.
  * Users do not need to spend time to make not an important exam again and again. And they can spend less time to modify and update their exam.

So my suggestion:
* Once `Release result` activated, I suggest we should add some notice to the `Form name` , for example: "Final test Grade 6 20-21 ( Result already released )" so we can easily track which exam have already completely done.
  * Have an option to withhold the result?
* OR
    * Change `Release result` position to the column next to `Remaining duration` after the exam ended.
 
![Release result 2](https://user-images.githubusercontent.com/87641533/129514826-901e489b-dfc4-4e29-b4f5-a7a484992a85.png)

### Browsers

**Comment by bugless-it** [comment]
@nagthanm if i understand correctly, you'd an option to **un**release the exam result?

**Comment by nagthanm** [comment]
Yes, I suggest an option to unrelease the exam results. And I wonder why you choose not to withhold them. 🤔

**Comment by bugless-it** [comment]
@nagthanm I've added that feature. I think originally i decided not to add it is because teachers might reuse questions in a new question form instead of reusing the same one.

**Comment by nagthanm** [comment]
@bugless-it Ok, I understand your point now. In my opinion, unrelease the exam result still a convenience feature.
I checked the feature on the app and I have no more suggestion.
For now, this issue will be closed. If there are more suggestions from users and from us in the future, I will reopen this issue for further  discussion.
