### ISSUE TITLE
"Reuse Questions" Title?

### ISSUE THREAD

**Issue by nagthanm** [fit-together-tv/ft-issue-report#15]
### Reproduction Steps
* Open `app.chuongnau.com`
* Open `Add new form` or `View question from`
* `Reuse Question`

### Expect behavior
Do you think we should have a tab for the unit number and title? 
For example: unit 1 my hobbies, unit 2 health, Unit 3 Community service, so the teacher can easily compile exercise for practice?
I think the teachers might want the student to follow and practice each units step by step. 

### Browser

**Comment by bugless-it** [comment]
@nagthanm are those units based on the book's order?

I think we can add them as tags, so they can be searchable as well, e.g. tags `my hobbies`, `community service` etc. What do you think?

**Comment by nagthanm** [comment]
Yes, Iooked at the books from other authors and find out they have the same units title. So I suppose their units follow the main line. If the users do not want to show the title, they can remove the tags by themselves. 
Do you think we should add the unit number or just only the title: `Unit 1 my hobbies` or just `my hobbies`

**Comment by bugless-it** [comment]
We can actually add both @nagthanm, but it depends on whether we have that information in the question sheet?

**Comment by bugless-it** [comment]
@nagthanm we can add as many as we want:
- Unit 1 My hobbies
- My hobbies
- etc

**Comment by nagthanm** [comment]
Ok, so I will try to make it as simple and clear as possible.
I will close this issue now!
