### ISSUE TITLE
Set start time: mobile users experience

### ISSUE THREAD

**Issue by nagthanm** [fit-together-tv/ft-issue-report#4]
### Reproduction Steps
* Open [app.chuongnau.com](https://app.chuongnau.com/me).
* Choose "add new form" to build a new question form / or choose "view question form" if more than one was created.
*  Choose tab "Publish tests and answers"
*  "Create exam"
*  "Set start time"

### User experience
Some inconvinient user experience when I try to scroll or slide up and down to choose hour, minute and second.
![IMG_3795](https://user-images.githubusercontent.com/87641533/127125406-f3146e53-8bde-42bd-b135-36600a500f28.PNG)
![IMG_3796](https://user-images.githubusercontent.com/87641533/127125419-7152b6ae-6d56-40ac-992f-f3e1adf8aeb8.PNG)

### Suggest Improvements
A friendly mobile user.
For example
![IMG_3710](https://user-images.githubusercontent.com/87641533/127125443-958f344c-1aed-4ca5-9d0d-a6fc02b6fd8d.PNG)

### Device: 
iOS, Android.

### Browser
Mobile browsers.

**Comment by protoman92** [comment]
Let me take a look at this.

**Comment by bugless-it** [comment]
Fixed this in latest app version, @nagthanm please have a look. Please help check the following flow as well:
- User participates in a question form and needs to input their date of birth.

**Comment by nagthanm** [comment]
Hi, the new interface for preset exam time is very convenient and friendly for mobile user.
For your following request, I will open new thread and close this issue now.

**Comment by bugless-it** [comment]
Thanks @nagthanm!

**Comment by nagthanm** [comment]
"User participates in a question form and needs to input their date of birth." Run perfectly in mobile interface.
