### ISSUE TITLE
Exported GG form status code 500

### ISSUE THREAD

**Issue by nagthanm** [fit-together-tv/ft-issue-report#8]
### Reproduction Steps
+ Open [app.chuongnau.com](https://app.chuongnau.com/me)
+ "add new form"/ or choose "view question form" for an existed question form.
+ Choose "Export to Google Form"
+ Click "Exported to new Google Form"
+ Click OK

### Actual Behavior
+ request failed with status code 500 from 3:43 PM Vietnam TimeZone. 7/31/21. Just a few minutes before at around 3:39 PM, the Exported still stable.

### Expected Behavior
"Export to Google Form" run fine with no status code.

### Device 
PC Windows 10

### Browser 
MS Edge.

![Exported GG form status code 500](https://user-images.githubusercontent.com/87641533/127734909-8e8a4799-8b09-4873-97a7-24686bc70d9c.png)

**Comment by bugless-it** [comment]
Problem was due to invalid Google token - it should be solved now. @nagthanm could you take a look again?

**Comment by nagthanm** [comment]
problem solved

**Comment by nagthanm** [comment]
The bug is only occurred on the initial stage of exporting GG form. After users log out and sign in again, the problem is resolved.

Problem solved now.
